Improve error handling from AOS requests
microsoft/SCMScaleUnitDevTools pull request #110
Opened 2021-10-26 13:21 UTC by Antonstockmarr

ReliableRun class will catch AOS exceptions and try to suggest changes. Other errors pass through. If a suggestion is found, or it does not make sense to retry, the request is not repeated. Every AOS error is shown to the user.

Example of an error with an inline TSG:
![image](https://user-images.githubusercontent.com/43210147/138887226-b08febfb-2e5c-4776-b4e6-f6c45a23aef1.png)

resolves #105
#patch

2021-11-03 07:30 UTC, AndreasHassing approved these changes

2021-11-05 13:06 UTC, AndreasHassing requested changes

2021-11-05 13:06 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/ReliableRun.cs
> +                catch (AOSClientError e)
Timeout exceptions and similar will not be `AOSClientError` (you only throw such an exception type if `IsSuccessStatusCode` is false - if `httpClient.SendAsync` or `response.Content.ReadAsStringAsync` throws, you won't catch it here and retry.

2021-11-18 21:57 UTC, AndreasHassing commented
@Antonstockmarr this PR is ready except that it needs to uptake `main`, please merge `main` into this and ensure things look good - then ping @Omaaarz or me and we can get it in 😊. Thanks!

2021-11-18 21:59 UTC, AndreasHassing approved these changes

2021-11-22 14:47 UTC, Omaaarz approved these changes

2021-11-22 14:49 UTC, merged