Delete and truncate problematic tables #patch
microsoft/SCMScaleUnitDevTools pull request #115
Opened 2021-11-05 10:42 UTC by Antonstockmarr

The step to "truncate potentially problematic tables" left out tables that might cause issues. Only the NumberSequenceReference tables was truncated. NumberSequenceScope and NumberSequenceTable had rows that were related, but they were not deleted.
The step to remove problematic tables is now part of scale Unit Installation. This means that NumberSequence records can no longer be created between initializing the environment and installing workloads, which could cause the SYS package to fail.
This has been tested by running full deployment on SingleOnebox.
Resolves #113

2021-11-05 11:17 UTC, AndreasHassing requested changes

2021-11-05 11:17 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +            DELETE FROM SysFeatureStateV0;
[nit] Just use `TRUNCATE` for all of these.

2021-11-05 11:17 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +            EXEC sys.sp_set_session_context @key = N'ActiveScaleUnitId', @value = '@A';
Not `@A`, but whatever the scale unit's mnemonic is.

2021-11-05 11:17 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                    ClearPotentiallyProblematicTables();
I don't know 100%, but it's probably safer to put this down right before the `WriteWorkloadInstances`, as the workload could already be in installing state with the package just having been applied (race condition where it's about to set the state to Ready), but then we truncate the data from the initial SYS application and are in a bad state.

2021-11-05 12:16 UTC, Antonstockmarr commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                    ClearPotentiallyProblematicTables();
You're right! If we try to run Install Workloads while SYS is already being installed, these lines will clear the tables and move on, leaving us in a bad state.

2021-11-05 12:38 UTC, AndreasHassing requested changes

2021-11-05 12:38 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +            TRUNCATE FROM SysFeatureStateV0;
`TRUNCATE TABLE`

2021-11-05 12:38 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
>                      await scaleUnitAosClient.WriteWorkloadInstances(workloadInstanceToInstallList);
Consider putting it immediately after the `WriteWorkloadInstances` - I have a hunch that this call in itself can add those bad records.

2021-11-05 12:57 UTC, Antonstockmarr commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
>                      await scaleUnitAosClient.WriteWorkloadInstances(workloadInstanceToInstallList);
Hm, but I thought the ``WriteWorkloadInstances`` required these tables to be cleared first. Isn't it risky to first wait for this call to go through and then clear the tables? That could also put us in a bad state. If the query to clear the table can create new entries on its own, how can we ever assume that we have cleared these tables?

2021-11-05 13:10 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
>                      await scaleUnitAosClient.WriteWorkloadInstances(workloadInstanceToInstallList);
Actually, it's the first SYSHTS upload session on the scale unit that fails when these tables are not cleared first; that upload session is applied some time after `WriteWorkloadInstances` has already succeeded the first time.

2021-11-09 10:00 UTC, Omaaarz requested changes

2021-11-09 10:00 UTC, Omaaarz commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                    if (WorkloadInstanceManager.IsSYSWorkload(workloadInstance))
We can have multiple SYS workload installed and we don't want to clean up these tables on the second SYS workload installation

2021-11-09 10:28 UTC, Antonstockmarr commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                    if (WorkloadInstanceManager.IsSYSWorkload(workloadInstance))
We should make sure that there are no running workloads on the scale unit before clearing the tables.

2021-11-09 10:51 UTC, AndreasHassing commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                    if (WorkloadInstanceManager.IsSYSWorkload(workloadInstance))
Good catch!

2021-11-09 13:33 UTC, Omaaarz commented on src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
> +                        if (await CountInstalledWorkloads(scaleUnitAosClient) == 0)
I believe we should be getting the # of installed workloads before writing the workload instances save it to a variable and do only the check here.

2021-11-12 10:10 UTC, Omaaarz approved these changes

2021-11-12 13:24 UTC, Antonstockmarr commented
Tested using the single execution deploy option, everything works as expected

2021-11-12 14:13 UTC, merged