Creating Setup Tools menu, which allows syncing both the Hub and the ScaleUnit.
microsoft/SCMScaleUnitDevTools pull request #67
Opened 2021-07-26 14:41 UTC by Antonstockmarr

Added a new option to the start menu: "Setup Tools". From here the user can sync the HubDB, or select a ScaleUnit to sync. The scale units only appear if UseSingleOneBox is true.

2021-07-30 10:06 UTC, Antonstockmarr commented
Resolves #35

2021-08-02 10:18 UTC, Omaaarz commented on src/CLI/SyncDB.cs
> +
nit: extra empty non needed line

2021-08-02 10:24 UTC, Omaaarz commented on src/CLI/SyncDB.cs
> +            if (Config.UseSingleOneBox())
Why are we branching here?

I guess we can always do what is in the current if body.

2021-08-02 10:31 UTC, Omaaarz commented on src/CLI/SyncDB.cs
> +        private static async Task SyncHubDB(int input, string selectionHistory)
No need for different methods for hub and spoke DBsync. You can always use the implementation of SyncSpokeDB method but you might need to rename it to be generic (ex: syncDB)

2021-08-02 10:32 UTC, Omaaarz requested changes
Left some comments to address

2021-08-02 10:52 UTC, Antonstockmarr commented on src/CLI/SyncDB.cs
> +            if (Config.UseSingleOneBox())
What if a user tries to sync a spoke that is not running on the same machine as the hub? Can that happen, and would the DBsync still work as expected?

2021-08-02 11:03 UTC, Omaaarz commented on src/CLI/SyncDB.cs
> +            if (Config.UseSingleOneBox())
If the DB isn't existing in the current machine, then DB sync would fail. If both envs DBs have the same name, then it would sync the hub db instead (I guess that's still not a problem). 

But looking at what you providing, then in non single box setup, there will be no way to sync spokes(scale units). You will only sync hub which isn't correct.

It will be the responsibility of the developer that runs the operation in the correct environment. I guess we are doing the same for (initialize hybrid topology) step.

2021-08-02 11:08 UTC, Antonstockmarr commented on src/CLI/SyncDB.cs
> +            if (Config.UseSingleOneBox())
Okay, I see what you mean. The user cannot sync the spoke in non-singleBox setup. I will correct it.

2021-08-03 07:56 UTC, Omaaarz commented on src/CLI/SetupTools.cs
> +
nit: empty line

2021-08-03 08:01 UTC, Omaaarz approved these changes
LGTM. left 1 minor comment.

2021-08-03 08:29 UTC, merged