Replace use of Powershell scripts using SqlClient and Process.Start #patch
microsoft/SCMScaleUnitDevTools pull request #70
Opened 2021-08-13 11:22 UTC by Antonstockmarr

CommandExecutor can now execute commands without PowerShell using `Process.Start`.
`Invoke-SqlCmd` has been removed. Instead `SqlCommand` is used to query the database.

Resolves remaining items on #10

2021-08-17 09:02 UTC, AndreasHassing requested changes
RFC, looks good other than a few nits 😊.

2021-08-17 10:10 UTC, Antonstockmarr commented on src/ScaleUnitManagement/ScaleUnitFeatureManager/Common/RunDBSync.cs
> +                    "-syncmode=\"fullall\""
I did test this, and it does work. I believe the reason is that before the operation was called using Process.Start(), with file name set to "powershell". This meant that the string had to be parsed first by the Process object, and then afterwards by PowerShell. So the qoutes needed to be wrapped twice. But now the command is run directly by Process.Start(), with the file name set directly to the dbsSync executable. So the double wrapped quotes are not needed.

2021-08-17 12:43 UTC, AndreasHassing requested changes
Fix use of `params` and we're golden. Thanks for this Anton! 👍

2021-08-17 12:43 UTC, AndreasHassing commented on src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/IISAdministrationHelper.cs
> +            ce.RunCommand(new int[] { 0, 1 });
The cool thing about `params` is that you can now use `RunCommand` like:

```csharp
ce.RunCommand(); // assumes an empty array
ce.RunCommand(1); // passes in a: `new int[] { 1 }`
ce.RunCommand(0, 1); // passes in a: `new int[] { 0, 1 }`
```

2021-08-17 12:46 UTC, Antonstockmarr commented on src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/IISAdministrationHelper.cs
> +            ce.RunCommand(new int[] { 0, 1 });
Ahh, okay that's really cool!

2021-08-18 08:57 UTC, AndreasHassing approved these changes

2021-08-18 09:03 UTC, merged